wandb_version: 1

max_depth:
  desc: null
  value: 10
min_samples_split:
  desc: null
  value: 12
n_estimators:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    python_version: 3.10.2
    cli_version: 0.16.1
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722894653.90739
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.2
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    viz:
      feature_importances:
        id: wandb/feature_importances/v1
        historyFieldSettings:
          x-axis: _step
          key: feature_importances
