wandb_version: 1

max_depth:
  desc: null
  value: null
min_samples_split:
  desc: null
  value: 2
n_estimators:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    python_version: 3.10.2
    cli_version: 0.16.1
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722893434.066965
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 3
      - 23
      - 37
      4: 3.10.2
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      10:
      - 5
      13: windows-amd64
    viz:
      feature_importances:
        id: wandb/feature_importances/v1
        historyFieldSettings:
          x-axis: _step
          key: feature_importances
      confusion_matrix:
        id: wandb/confusion_matrix/v1
        historyFieldSettings:
          x-axis: _step
          key: confusion_matrix
      summary_metrics:
        id: wandb/metrics/v1
        historyFieldSettings:
          x-axis: _step
          key: summary_metrics
      class_proportions:
        id: wandb/class_proportions/v1
        historyFieldSettings:
          x-axis: _step
          key: class_proportions
      calibration_curve:
        id: wandb/calibration/v1
        historyFieldSettings:
          x-axis: _step
          key: calibration_curve
      roc:
        id: wandb/roc/v1
        historyFieldSettings:
          x-axis: _step
          key: roc
      precision_recall:
        id: wandb/pr_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: precision_recall
