wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.2
    cli_version: 0.16.1
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722965709.362023
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.10.2
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
